### ISSUE TITLE
Program does not support building networks.

### ISSUE THREAD

**Issue by ahkneipp** [savagewil/NetworkMapper#2]
You know, the basic purpose of this program.

**Comment by ahkneipp** [comment]
The question is, do we want to do this directly off of the traceroute or put a step in between

**Comment by savagewil** [comment]
We should do a  ping scan for everything we want to look for.
Next, an empty adjacency matrix should be generated.
Then we should run a traceroute to each of these, one by one, then add the connections to the adjacency matrix.

**Comment by ahkneipp** [comment]
Agreed

**Comment by ahkneipp** [comment]
Wait, not agreed.  We should generate an OS-independant list of connections (It doesn't have to be a list, but that might be useful) from each OSs traceroute command, then use that to build the matrix.  If we pull it straight into the matrix, we'll each have to write our own matrix populating code.
