### ISSUE TITLE
Program has poor resource management

### ISSUE THREAD

**Issue by ahkneipp** [savagewil/NetworkMapper#3]
When I ran the program and looked at the open processes in the system, there were hundreds of defunct ping processes and far more live pings open than there should be.  I suspect the program exists in both supported operating systems.

The resource management doesn't affect the program's effectiveness when run stand-alone in a terminal, but it does prevent it from running in PyCharm IDE.  Low priority for now.

**Comment by savagewil** [comment]
I added a function to kill each process when we are done with them.

**Comment by ahkneipp** [comment]
Let me check if it solves the problem, then I'll close the issue.

**Comment by ahkneipp** [comment]
Left no defunct processes and only opened the proper amount but then tried to kill a non-existent process.  I'll see if I can find the issue

**Comment by ahkneipp** [comment]
Found an issue.  I'll push my changes because they fix the non-existent process issue but I'll reopen another compatibility issue
